Check if some command actually was actually provided

diff --git a/git-watch b/git-watch
--- a/git-watch
+++ b/git-watch
@@ -77,13 +77,17 @@ done
 
 # Test git repository and start execution
 
-if git rev-parse --git-dir > /dev/null 2>&1; then
+if !(git rev-parse --git-dir > /dev/null 2>&1); then
+    echo "Error: not a git repository"
+    exit 1
+elif [[ -z "$@" ]]; then
+    echo "Please provide update command to run on updates."
+    exit 1
+else
     if [ $async = true ]; then
         run "$@" &
         echo "Started background job with PID $!"
     else
         (run "$@")
     fi
-else
-	echo "Error: not a git repository"
 fi
